#!/usr/bin/env python3
BASE_DIR = "/home/erikt/projects/ree-hdsc/ree-hdsc/website/"
PRIVATE_DIR = f"{BASE_DIR}private"

import sys
sys.stderr = open(f"{BASE_DIR}etc/errorlog", "a")

import os
os.chdir(PRIVATE_DIR)

os.environ["PYTHONPATH"] = PRIVATE_DIR
sys.path.append(PRIVATE_DIR)

from wsgiref.handlers import CGIHandler
from annotate import app

CGIHandler().run(app)

sys.exit(0)
