PRINTED_TEXT = {}

PRINTED_TEXT[0] = []

PRINTED_TEXT[1831] = [
    "No",
    "Verbeteringen",
    "Heden den",
    "Compareerden voor mij",
    "ambtenaar",
    "van den Burgerlijken stand op dit eiland",
    "De personen van",
    "van competenten ouderdom en alhier woonachtig",
    "Dewelke aangifte hebben gedaan dat",
    "op den",
    "des Jaars Een duizend acht honderd",
    "te",
    "ure des",
    "overleden is",
    "Oud",
    "Geboren",
    "op den",
    "zijnde",
    "laatstelijk gewoond",
    "En is deze behoorlijk geteekend",
    "op Curacao dato utsupra",
    "niet te kunnen schrijven",
    "Aanteekeningen",
]

PRINTED_TEXT[1842] = [
    "No",
    "Verbeteringen",
    "Heden den",
    "des Jaars Een duizend acht honderd",
    "Compareerden voor mij",
    "ambtenaar",
    "van den Burgerlijken stand op dit eiland",
    "De personen van",
    "van competenten ouderdom en alhier woonachtig",
    "Dewelke aangifte hebben gedaan dat",
    "op dit eiland",
    "op den",
    "des Jaars Een duizend acht honderd",
    "te",
    "ure des",
    "overleden is",
    "Oud",
    "naar gissing",
    "Geboren",
    "op den",
    "des Jaars Een duizend acht honderd",
    "laatstelijk gewoond",
    "En is deze behoorlijk geteekend",
    "na voorlezing",
    "op Curacao dato utsupra",
    "niet te kunnen schrijven",
    "F",
    "Aanteekeningen",
]

PRINTED_TEXT[1859] = [
    "No",
    "Verbeteringen",
    "Heden den",
    "des Jaars Een duizend acht honderd",
    "Compareerden voor mij",
    "ambtenaar",
    "van den Burgerlijken stand op dit eiland",
    "De personen van",
    "van competenten ouderdom en alhier woonachtig, dewelke aangifte hebben gedaan dat",
    "op dit eiland",
    "op den",
    "des Jaars Een duizend acht honderd",
    "te",
    "ure des",
    "overleden is",
    "Oud",
    "naar gissing",
    "Geboren",
    "op den",
    "des Jaars Een duizend acht honderd",
    "laatstelijk gewoond",
    "En is deze behoorlijk geteekend",
    "na voorlezing",
    "op Curacao dato utsupra",
    "niet te kunnen schrijven",
    "F",
    "Aanteekeningen",
]

PRINTED_TEXT[1869] = [
    "Folio",
    "No",
    "Heden den",
    "des Jaars",
    "Een duizend acht honderd en",
    "Compareerden ten burele voor mij",
    "ambtenaar van den Burgerlijken stand in het",
    "district dezes eilands",
    "De personen van",
    "van beroep",
    "oud",
    "wonende",
    "en",
    "van beroep",
    "oud",
    "wonende",
    "dewelke aangifte hebben gedaan",
    "op den",
    "des Jaars Een duizend acht honderd en",
    "te",
    "ure des",
    "overleden is",
    "in den ouderdom van",
    "jaren",
    "van",
    "zijnde geboren",
    "En is hiervan akte opgemaakt, welke na voorlezing door de",
    "en mij",
    "ambtenaar",
    "voormeld is ondertekendteekend",
    "op Curacao dato utsupra",
]

PRINTED_TEXT[1873] = [
    "Folio",
    "No",
    "Heden den",
    "des Jaars",
    "Een duizend acht honderd en",
    "Compareerden ten burele voor mij",
    "ambtenaar van den Burgerlijken stand in het",
    "district dezes eilands",
    "De personen van",
    "van beroep",
    "oud",
    "wonende",
    "en",
    "van beroep",
    "oud",
    "wonende",
    "dewelke aangifte hebben gedaan",
    "op den",
    "des Jaars Een duizend acht honderd en",
    "te",
    "ure des",
    "overleden is",
    "in den ouderdom van",
    "jaren",
    "van",
    "zijnde geboren",
    "En is hiervan acte opgemaakt, welke na voorlezing door de",
    "en mij ambtenaar voormeld",
    "is onderteekend",
    "op Curacao dato utsupra",
]

PRINTED_TEXT[1880] = [
    "Folio",
    "No",
    "Heden den",
    "des Jaars",
    "Een duizend acht honderd en",
    "Compareerden ten burele voor mij",
    "ambtenaar van den Burgerlijken stand in het",
    "district dezes eilands",
    "De personen van",
    "van beroep",
    "oud",
    "wonende",
    "en",
    "van beroep",
    "oud",
    "wonende",
    "dewelke aangifte hebben gedaan",
    "op den",
    "des Jaars Een duizend acht honderd en",
    "te",
    "ure des",
    "overleden is",
    "in den ouderdom van",
    "jaren",
    "van",
    "zijnde geboren",
    "En is hiervan acte opgemaakt, welke na voorlezing door de",
    "en mij ambtenaar",
    "voormeld is onderteekend",
    "op Curacao dato utsupra",
]

PRINTED_TEXT[1885] = [
    "Folio",
    "No",
    "Heden den",
    "des Jaars",
    "Een duizend acht honderd en",
    "Compareerden ten burele voor mij",
    "ambtenaar van den Burgerlijken stand in het",
    "district dezes eilands",
    "De personen van",
    "van beroep",
    "oud",
    "wonende",
    "en",
    "van beroep",
    "oud",
    "wonende",
    "dewelke aangifte hebben gedaan dat in het",
    "district alhier op den",
    "des Jaars Een duizend acht honderd en",
    "te",
    "ure des",
    "overleden is",
    "in den ouderdom van",
    "jaren",
    "van",
    "zijnde geboren",
    "En is hiervan acte opgemaakt, welke na voorlezing door de",
    "en mij ambtenaar voormeld",
    "is onderteekend",
    "op Curacao dato utsupra",
]


PRINTED_TEXT[1892] = [
    "Folio",
    "No",
    "Heden den",
    "des Jaars",
    "Een duizend acht honderd en",
    "en negentig",
    "Compareerden ten burele voor mij",
    "ambtenaar van den Burgerlijken stand in het",
    "district dezes eilands",
    "De personen van",
    "van beroep",
    "oud",
    "jaren",
    "wonende alhier",
    "en",
    "van beroep",
    "oud",
    "jaren",
    "wonende alhier",
    "dewelke aangifte hebben gedaan dat in het",
    "district alhier op den",
    "des Jaars Een duizend acht honderd en",
    "en negentig",
    "te",
    "ure des",
    "overleden is",
    "in den ouderdom van",
    "jaren",
    "van",
    "zijnde geboren",
    "En is hiervan acte opgemaakt, welke na voorlezing door de",
    "en mij ambtenaar voor",
    "meld is onderteekend",
    "op Curacao dato utsupra",
]

PRINTED_TEXT[1894] = [
    "Folio",
    "No",
    "Heden den",
    "des Jaars",
    "Een duizend acht honderd en",
    "en negentig",
    "compareerden ten burele voor mij",
    "ambtenaar van den Burgerlijken stand in het",
    "district dezes eilands",
    "De personen van",
    "van beroep",
    "oud",
    "jaren",
    "wonende alhier",
    "en",
    "van beroep",
    "oud",
    "jaren",
    "wonende alhier",
    "dewelke aangifte hebben gedaan dat in het",
    "district alhier op den",
    "des Jaars Een duizend acht honderd en",
    "en negentig",
    "te",
    "ure des",
    "overleden is",
    "in den ouderdom van",
    "jaren",
    "van",
    "zijnde geboren",
    "En is hiervan acte opgemaakt, welke na voorlezing door de",
    "en mij ambtenaar voor",
    "meld is onderteekend",
    "op Curacao dato utsupra",
]

PRINTED_TEXT[1895] = [
    "Folio",
    "No",
    "Heden den",
    "des Jaars",
    "Een duizend acht honderd en",
    "en negentig",
    "compareerden ten burele voor mij",
    "ambtenaar van den Burgerlijken stand in het",
    "district dezes eilands",
    "De personen van",
    "van beroep",
    "oud",
    "jaren",
    "wonende alhier",
    "en",
    "van beroep",
    "oud",
    "jaren",
    "wonende alhier",
    "dewelke aangifte hebben gedaan dat in het",
    "district alhier op den",
    "des Jaars Een duizend acht honderd en",
    "en negentig",
    "te",
    "ure des",
    "overleden is",
    "in den ouderdom van",
    "jaren",
    "van",
    "zijnde geboren",
    "En is hiervan acte opgemaakt, welke na voorlezing door de",
    "en mij ambtenaar voor",
    "meld is onderteekend",
    "op Curacao dato utsupra",
]

PRINTED_TEXT[1900] = [
    "Folio",
    "No",
    "Heden den",
    "des Jaars",
    "Een duizend negen honderd",
    "compareerde voor mij",
    "ambtenaar van den Burgerlijken stand in het",
    "district dezes eilands ten mijnen bureele",
    "De personen van",
    "van beroep",
    "oud",
    "jaren",
    "wonende alhier",
    "en",
    "van beroep",
    "oud",
    "jaren",
    "wonende alhier",
    "dewelke aangifte hebben gedaan dat in het",
    "district alhier op den",
    "des Jaars Een duizend negen honderd",
    "te",
    "ure des",
    "overleden is",
    "in den ouderdom van",
    "jaren",
    "van",
    "zijnde geboren",
    "En is hiervan acte opgemaakt, welke na voorlezing door de",
    "en mij ambtenaar voor",
    "meld is onderteekend op Curacao dato utsupra",
]

PRINTED_TEXT[1907] = [
    "Folio",
    "No",
    "Heden den",
    "des Jaars",
    "Een duizend negen honderd",
    "compareerden",
    "voor mij ambtenaar van den Burgerlijken stand in het",
    "district dezes eilands ten mijnen bureele",
    "De personen van",
    "van beroep",
    "oud",
    "jaren",
    "wonende alhier",
    "en",
    "van beroep",
    "oud",
    "jaren",
    "wonende alhier",
    "dewelke aangifte hebben gedaan dat in het",
    "district alhier op den",
    "des Jaars Een duizend negen honderd",
    "te",
    "ure des",
    "overleden is",
    "in den ouderdom van",
    "jaren",
    "van",
    "zijnde geboren",
    "En is hiervan acte opgemaakt, welke na voorlezing door de",
    "en mij ambtenaar voormeld",
    "is onderteekend op Curacao dato utsupra",
]

PRINTED_TEXT[1909] = [
    "Folio",
    "No",
    "Heden den",
    "des Jaars",
    "Een duizend negen honderd",
    "compareerden",
    "voor mij",
    "ambtenaar van den Burgerlijken stand in het",
    "district dezes eilands ten mijnen bureele",
    "De personen van",
    "van beroep",
    "oud",
    "jaren",
    "wonende alhier",
    "en",
    "van beroep",
    "oud",
    "jaren",
    "wonende alhier",
    "dewelke aangifte hebben gedaan dat in het",
    "district alhier op den",
    "des Jaars Een duizend negen honderd",
    "te",
    "ure des",
    "overleden is",
    "in den ouderdom van",
    "jaren",
    "van",
    "zijnde geboren",
    "En is hiervan acte opgemaakt, welke na voorlezing door de",
    "en mij ambtenaar",
    "voormeld is onderteekend op Curacao dato utsupra",
]

PRINTED_TEXT[1925] = [
    "Folio",
    "No",
    "Heden den",
    "des Jaars",
    "Een duizend negen honderd",
    "compareerden",
    "voor mij hulpambtenaar van den Burgerlijken stand in het",
    "district dezes eilands ten mijnen bureele",
    "De personen van",
    "van beroep",
    "oud",
    "jaren",
    "wonende alhier in het",
    "district",
    "en",
    "van beroep",
    "oud",
    "jaren",
    "wonende alhier in het",
    "district",
    "dewelke aangifte hebben gedaan dat in het",
    "district alhier op den",
    "des Jaars Een duizend negen honderd",
    "te",
    "ure des",
    "overleden is",
    "in den ouderdom van",
    "jaren",
    "van",
    "zijnde geboren",
    "En is hiervan acte opgemaakt, welke, na voorlezing door de",
    "en mij hulpambtenaar",
    "voormeld is onderteekend op Curacao dato utsupra",
]

PRINTED_TEXT[1935] = [
    "Folio",
    "No",
    "Heden den",
    "negentienhonderd",
    "verscheen voor mij, hulpambtenaar van den Burgerlijken Stand",
    "in het",
    "district op Curacao",
    "oud",
    "jaren, van beroep",
    "wonende in het",
    "district alhier die op grond van eigen wetenschap verklaarde dat in het",
    "dis",
    "trict alhier op den",
    "negentienhonderd",
    "ten",
    "ure des",
    "middags",
    "overleden is",
    "in den ouderdom van",
    "Waarvan akte, welke is voorgelezen",
]

PRINTED_TEXT[1937] = [
    "Folio",
    "No",
    "Heden den",
    "negentienhonderd",
    "verscheen voor mij, hulpambtenaar van den Burgerlijken Stand",
    "in het",
    "district op Curacao",
    "oud",
    "jaren, van beroep",
    "wonende in het",
    "district alhier die op grond van eigen wetenschap verklaarde dat in het",
    "district alhier op den",
    "negentienhonderd",
    "ten",
    "ure",
    "des",
    "middags overleden is",
    "in den ouderdom van",
    "Waarvan akte, welke is voorgelezen",
]

PRINTED_TEXT[1938] = [
    "No",
    "Folio",
    "Heden den",
    "negentienhonderd",
    "verscheen voor mij", 
    "hulpambtenaar van den Burgerlijken Stand",
    "oud",
    "jaren",
    "beroep",
    "wonende in het",
    "district op",
    "die op grond van eigen wetenschap verklaarde",
    "dat in het",
    "district op",
    "op den",
    "negentienhonderd",
    "ten",
    "ure des",
    "middags overleden is",
    "in den ouderdom van",
    "Waarvan akte, welke is voorgelezen",
]

PRINTED_TEXT[1939] = [
    "Nr",
    "Heden",
    "negentienhonderd negen en dertig verscheen voor mij, hulpambtenaar van",
    "den burgerlijken stand op Curacao",
    "oud",
    "jaren",
    "wonende alhier, die verklaarde, daarvan uit eigen wetenschap kennis",
    "dragende, dat op",
    "dezes jaars",
    "des",
    "middags te",
    "uur, alhier is overleden",
    "Waarvan akte, welke is voorgelezen",
]

PRINTED_TEXT[1940] = [
    "Nr",
    "Heden",
    "negentienhonderd veertig verscheen voor mij, hulpambtenaar van den",
    "burgerlijken stand op Curacao",
    "oud",
    "jaren",
    "wonende alhier, die verklaarde, daarvan uit eigen wetenschap kennis",
    "dragende, dat op",
    "dezes jaars",
    "des",
    "middags te",
    "uur, alhier is overleden",
    "Waarvan akte, welke is voorgelezen",
]

PRINTED_TEXT[1941] = [
    "Nr",
    "Heden",
    "negentienhonderd een en veertig verscheen voor mij, hulpambtenaar van",
    "den burgerlijken stand op Curacao",
    "oud",
    "jaren",
    "wonende alhier, die verklaarde, daarvan uit eigen wetenschap kennis",
    "dragende, dat op",
    "dezes jaars",
    "des",
    "middags te",
    "uur, alhier is overleden",
    "Waarvan akte, welke is voorgelezen",
]

PRINTED_TEXT[1942] = [
    "Nr",
    "Heden",
    "negentienhonderd twee en veertig verscheen voor mij, hulpambtenaar van",
    "den burgerlijken stand op Curacao",
    "oud",
    "jaren",
    "wonende alhier, die verklaarde, daarvan uit eigen wetenschap kennis",
    "dragende, dat op",
    "dezes jaars",
    "des",
    "middags te",
    "uur, alhier is overleden",
    "Waarvan akte, welke is voorgelezen",
]

PRINTED_TEXT[1943] = [
    "Nr",
    "Heden",
    "negentienhonderd drie en veertig verscheen voor mij, hulpambtenaar van",
    "den burgerlijken stand op Curacao",
    "oud",
    "jaren",
    "wonende alhier, die verklaarde, daarvan uit eigen wetenschap kennis",
    "dragende, dat op",
    "dezes jaars",
    "des",
    "middags te",
    "uur, alhier is overleden",
    "Waarvan akte, welke is voorgelezen",
]

PRINTED_TEXT[1944] = [
    "Nr",
    "Heden",
    "negentienhonderd",
    "en veertig verscheen voor mij, hulpambtenaar van",
    "den burgerlijken stand op Curacao",
    "oud",
    "jaren",
    "wonende alhier, die verklaarde, daarvan uit eigen wetenschap kennis",
    "dragende, dat op",
    "dezes jaars",
    "des",
    "middags te",
    "uur, alhier is overleden",
    "Waarvan akte, welke is voorgelezen",
]

PRINTED_TEXT[1944] = [
    "Nr",
    "Heden",
    "negentienhonderd",
    "en veertig verscheen voor mij, hulpambtenaar van",
    "den burgerlijken stand op Curacao",
    "oud",
    "jaren",
    "wonende alhier, die verklaarde, daarvan uit eigen wetenschap kennis",
    "dragende, dat op",
    "dezes jaars",
    "des",
    "middags te",
    "uur, alhier is overleden",
    "Waarvan akte, welke is voorgelezen",
]

PRINTED_TEXT[1945] = [
    "Nr",
    "Heden",
    "negentienhonderd",
    "en veertig verscheen voor mij, hulpambtenaar",
    "van den burgerlijken stand op",
    "oud",
    "jaren",
    "wonende alhier, die verklaarde, daarvan uit eigen wetenschap kennis",
    "dragende, dat op",
    "dezes jaars",
    "des",
    "middags te",
    "uur, alhier is overleden",
    "Waarvan akte, welke is voorgelezen",
]

PRINTED_TEXT[1948] = [
    "Nr",
    "Heden",
    "negentienhonderd",
    "en veertig verscheen voor mij, hulpambtenaar van",
    "de burgerlijke stand op",
    "oud",
    "jaren",
    "wonende alhier, die verklaarde, daarvan uit eigen wetenschap kennis",
    "dragende, dat op",
    "dezes jaars",
    "des",
    "middags te",
    "uur, alhier is overleden",
    "Waarvan akte, welke is voorgelezen",
]

PRINTED_TEXT[1950] = [
    "Nr",
    "Heden",
    "negentienhonderd",
    "en vijftig verscheen voor mij, hulpambtenaar",
    "van de burgerlijke stand op",
    "oud",
    "jaren",
    "wonende alhier, die verklaarde, daarvan uit eigen wetenschap kennis",
    "dragende, dat op",
    "dezes jaars",
    "des",
    "middags te",
    "uur, alhier is overleden",
    "Waarvan akte, welke is voorgelezen",
]
