PRINTED_TEXT = {}

PRINTED_TEXT[1831] = [
    "No",
    "Verbeteringen",
    "Heden den",
    "des Jaars Een duizend acht honderd",
    "Compareerden voor mij",
    "ambtenaar",
    "van den Burgerlijken stand op dit eiland",
    "De personen van",
    "van competenten ouderdom en alhier woonachtig",
    "Dewelke aangifte hebben gedaan dat",
    "op den",
    "des Jaars Een duizend acht honderd",
    "te",
    "ure des",
    "overleden is",
    "Oud",
    "naar gissing",
    "Geboren",
    "op den",
    "des Jaars Een duizend acht honderd",
    "zijnde",
    "laatstelijk gewoond",
    "En is deze behoorlijk geteekend",
    "na voorlezing",
    "op Curaçao dato utsupra",
    "niet te kunnen schrijven",
    "F",
    "Aanteekeningen",
]

PRINTED_TEXT[1842] = [
    "No",
    "Verbeteringen",
    "Heden den",
    "des Jaars Een duizend acht honderd",
    "Compareerden voor mij",
    "ambtenaar",
    "van den Burgerlijken stand op dit eiland",
    "De personen van",
    "van competenten ouderdom en alhier woonachtig",
    "Dewelke aangifte hebben gedaan dat",
    "op dit eiland",
    "op den",
    "des Jaars Een duizend acht honderd",
    "te",
    "ure des",
    "overleden is",
    "Oud",
    "naar gissing",
    "Geboren",
    "op den",
    "des Jaars Een duizend acht honderd",
    "laatstelijk gewoond",
    "En is deze behoorlijk geteekend",
    "na voorlezing",
    "op Curaçao dato utsupra",
    "niet te kunnen schrijven",
    "F",
    "Aanteekeningen",
]

PRINTED_TEXT[1859] = [
    "No",
    "Verbeteringen",
    "Heden den",
    "des Jaars Een duizend acht honderd",
    "Compareerden voor mij",
    "ambtenaar",
    "van den Burgerlijken stand op dit eiland",
    "De personen van",
    "van competenten ouderdom en alhier woonachtig, dewelke aangifte hebben gedaan dat",
    "op dit eiland",
    "op den",
    "des Jaars Een duizend acht honderd",
    "te",
    "ure des",
    "overleden is",
    "Oud",
    "naar gissing",
    "Geboren",
    "op den",
    "des Jaars Een duizend acht honderd",
    "laatstelijk gewoond",
    "En is deze behoorlijk geteekend",
    "na voorlezing",
    "op Curaçao dato utsupra",
    "niet te kunnen schrijven",
    "F",
    "Aanteekeningen",
]

PRINTED_TEXT[1869] = [
    "Folio",
    "No",
    "Heden den",
    "des Jaars",
    "Een duizend acht honderd en",
    "Compareerden ten burele voor mij",
    "ambtenaar van den Burgerlijken stand in het",
    "district dezes eilands",
    "De personen van",
    "van beroep",
    "oud",
    "wonende",
    "en",
    "van beroep",
    "oud",
    "wonende",
    "dewelke aangifte hebben gedaan",
    "op den",
    "des Jaars Een duizend acht honderd en",
    "te",
    "ure des",
    "overleden is",
    "in den ouderdom van",
    "jaren",
    "van",
    "zijnde geboren",
    "En is hiervan akte opgemaakt, welke na voorlezing door de",
    "en mij",
    "ambtenaar",
    "voormeld is ondertekendteekend",
    "op Curaçao dato utsupra",
]

PRINTED_TEXT[1873] = [
    "Folio",
    "No",
    "Heden den",
    "des Jaars",
    "Een duizend acht honderd en",
    "Compareerden ten burele voor mij",
    "ambtenaar van den Burgerlijken stand in het",
    "district dezes eilands",
    "De personen van",
    "van beroep",
    "oud",
    "wonende",
    "en",
    "van beroep",
    "oud",
    "wonende",
    "dewelke aangifte hebben gedaan",
    "op den",
    "des Jaars Een duizend acht honderd en",
    "te",
    "ure des",
    "overleden is",
    "in den ouderdom van",
    "jaren",
    "van",
    "zijnde geboren",
    "En is hiervan acte opgemaakt, welke na voorlezing door de",
    "en mij ambtenaar voormeld",
    "is onderteekend",
    "op Curaçao dato utsupra",
]

PRINTED_TEXT[1885] = [
    "Folio",
    "No",
    "Heden den",
    "des Jaars",
    "Een duizend acht honderd en",
    "Compareerden ten burele voor mij",
    "ambtenaar van den Burgerlijken stand in het",
    "district dezes eilands",
    "De personen van",
    "van beroep",
    "oud",
    "wonende",
    "en",
    "van beroep",
    "oud",
    "wonende",
    "dewelke aangifte hebben gedaan dat in het",
    "district alhier op den",
    "des Jaars Een duizend acht honderd en",
    "te",
    "ure des",
    "overleden is",
    "in den ouderdom van",
    "jaren,",
    "van",
    "zijnde geboren",
    "En is hiervan akte opgemaakt, welke na voorlezing door de",
    "en mij ambtenaar voormeld",
    "is ondertekeend",
    "op Curaçao dato utsupra",
]


PRINTED_TEXT[1892] = [
    "Folio",
    "No",
    "Heden den",
    "des Jaars",
    "Een duizend acht honderd en",
    "en negentig",
    "Compareerden ten burele voor mij",
    "ambtenaar van den Burgerlijken stand in het",
    "district dezes eilands",
    "De personen van",
    "van beroep",
    "oud",
    "jaren,",
    "wonende alhier",
    "en",
    "van beroep",
    "oud",
    "jaren,",
    "wonende alhier",
    "dewelke aangifte hebben gedaan dat in het",
    "district alhier op den",
    "des Jaars Een duizend acht honderd en",
    "en negentig",
    "te",
    "ure des",
    "overleden is",
    "in den ouderdom van",
    "jaren,",
    "van",
    "zijnde geboren",
    "En is hiervan akte opgemaakt, welke na voorlezing door de",
    "en mij ambtenaar voor-",
    "meld is onderteekend",
    "op Curaçao dato utsupra",
]

PRINTED_TEXT[1894] = [
    "Folio",
    "No",
    "Heden den",
    "des Jaars",
    "Een duizend acht honderd en",
    "en negentig",
    "compareerden ten burele voor mij",
    "ambtenaar van den Burgerlijken stand in het",
    "district dezes eilands",
    "De personen van",
    "van beroep",
    "oud",
    "jaren,",
    "wonende alhier",
    "en",
    "van beroep",
    "oud",
    "jaren,",
    "wonende alhier",
    "dewelke aangifte hebben gedaan dat in het",
    "district alhier op den",
    "des Jaars Een duizend acht honderd en",
    "en negentig",
    "te",
    "ure des",
    "overleden is",
    "in den ouderdom van",
    "jaren,",
    "van",
    "zijnde geboren",
    "En is hiervan akte opgemaakt, welke na voorlezing door de",
    "en mij ambtenaar voor-",
    "meld is onderteekend",
    "op Curaçao dato utsupra",
]

PRINTED_TEXT[1895] = [
    "Folio",
    "No",
    "Heden den",
    "des Jaars",
    "Een duizend acht honderd en",
    "en negentig",
    "compareerden ten burele voor mij",
    "ambtenaar van den Burgerlijken stand in het",
    "district dezes eilands",
    "De personen van",
    "van beroep",
    "oud",
    "jaren,",
    "wonende alhier",
    "en",
    "van beroep",
    "oud",
    "jaren,",
    "wonende alhier",
    "dewelke aangifte hebben gedaan dat in het",
    "district alhier op den",
    "des Jaars Een duizend acht honderd en",
    "en negentig",
    "te",
    "ure des",
    "overleden is",
    "in den ouderdom van",
    "jaren,",
    "van",
    "zijnde geboren",
    "En is hiervan akte opgemaakt, welke na voorlezing door de",
    "en mij ambtenaar voor-",
    "meld is onderteekend",
    "op Curaçao dato utsupra",
]

PRINTED_TEXT[1900] = [
    "Folio",
    "No",
    "Heden den",
    "des Jaars",
    "Een duizend negen honderd",
    "compareerde voor mij",
    "ambtenaar van den Burgerlijken stand in het",
    "district dezes eilands ten mijnen bureele",
    "De personen van",
    "van beroep",
    "oud",
    "jaren,",
    "wonende alhier",
    "en",
    "van beroep",
    "oud",
    "jaren,",
    "wonende alhier",
    "dewelke aangifte hebben gedaan dat in het",
    "district alhier op den",
    "des Jaars Een duizend negen honderd",
    "te",
    "ure des",
    "overleden is",
    "in den ouderdom van",
    "jaren,",
    "van",
    "zijnde geboren",
    "En is hiervan acte opgemaakt, welke na voorlezing door de",
    "en mij ambtenaar voor-",
    "meld is onderteekend op Curaçao dato utsupra",
]

PRINTED_TEXT[1907] = [
    "Folio",
    "No",
    "Heden den",
    "des Jaars",
    "Een duizend negen honderd",
    "compareerden",
    "voor mij ambtenaar van den Burgerlijken stand in het",
    "district dezes eilands ten mijnen bureele",
    "De personen van",
    "van beroep",
    "oud",
    "jaren,",
    "wonende alhier",
    "en",
    "van beroep",
    "oud",
    "jaren,",
    "wonende alhier",
    "dewelke aangifte hebben gedaan dat in het",
    "district alhier op den",
    "des Jaars Een duizend negen honderd",
    "te",
    "ure des",
    "overleden is",
    "in den ouderdom van",
    "jaren,",
    "van",
    "zijnde geboren",
    "En is hiervan acte opgemaakt, welke na voorlezing door de",
    "en mij ambtenaar voormeld",
    "is onderteekend op Curaçao dato utsupra",
]

PRINTED_TEXT[1909] = [
    "Folio",
    "No",
    "Heden den",
    "des Jaars",
    "Een duizend negen honderd",
    "compareerden",
    "voor mij",
    "ambtenaar van den Burgerlijken stand in het",
    "district dezes eilands ten mijnen bureele",
    "De personen van",
    "van beroep",
    "oud",
    "jaren,",
    "wonende alhier",
    "en",
    "van beroep",
    "oud",
    "jaren,",
    "wonende alhier",
    "dewelke aangifte hebben gedaan dat in het",
    "district alhier op den",
    "des Jaars Een duizend negen honderd",
    "te",
    "ure des",
    "overleden is",
    "in den ouderdom van",
    "jaren,",
    "van",
    "zijnde geboren",
    "En is hiervan acte opgemaakt, welke na voorlezing door de",
    "en mij ambtenaar",
    "voormeld is onderteekend op Curaçao dato utsupra",
]

PRINTED_TEXT[1925] = [
    "Folio",
    "No",
    "Heden den",
    "des Jaars",
    "Een duizend negen honderd",
    "compareerden",
    "voor mij hulpambtenaar van den Burgerlijken stand in het",
    "district dezes eilands ten mijnen bureele",
    "De personen van",
    "van beroep",
    "oud",
    "jaren,",
    "wonende alhier in het ",
    "district",
    "en",
    "van beroep",
    "oud",
    "jaren,",
    "wonende alhier in het",
    "district",
    "dewelke aangifte hebben gedaan dat in het",
    "district alhier op den",
    "des Jaars Een duizend negen honderd",
    "te",
    "ure des",
    "overleden is",
    "in den ouderdom van",
    "jaren,",
    "van",
    "zijnde geboren",
    "En is hiervan acte opgemaakt, welke, na voorlezing door de",
    "en mij hulpambtenaar",
    "voormeld is onderteekend op Curaçao dato utsupra",
]

PRINTED_TEXT[1935] = [
    "Folio",
    "No",
    "Heden den",
    "negentienhonderd",
    "verscheen voor mij, hulpambtenaar van den Burgerlijken Stand",
    "in het",
    "district op Curaçao",
    "oud",
    "jaren, van beroep",
    "wonende in het",
    "district alhier die op grond van eigen wetenschap verklaarde dat in het",
    "dis-",
    "trict alhier op den",
    "negentienhonderd",
    "ten",
    "ure des",
    "middags",
    "overleden is",
    "in den ouderdom van",
    "Waarvan akte, welke is voorgelezen",
]

PRINTED_TEXT[1937] = [
    "Folio",
    "No",
    "Heden den",
    "negentienhonderd",
    "verscheen voor mij, hulpambtenaar van den Burgerlijken Stand",
    "in het",
    "district op Curaçao",
    "oud",
    "jaren, van beroep",
    "wonende in het",
    "district alhier die op grond van eigen wetenschap verklaarde dat in het",
    "district alhier op den",
    "negentienhonderd",
    "ten",
    "ure",
    "des",
    "middags overleden is",
    "in den ouderdom van",
    "Waarvan akte, welke is voorgelezen",
]

PRINTED_TEXT[1938] = [
    "No",
    "Folio",
    "Heden den",
    "negentienhonderd",
    "verscheen voor mij", 
    "hulpambtenaar van den Burgerlijken Stand",
    "oud",
    "jaren,",
    "beroep,",
    "wonende in het",
    "district op",
    "die op grond van eigen wetenschap verklaarde",
    "dat in het",
    "district op",
    "op den",
    "negentienhonderd",
    "ten",
    "ure des",
    "middags overleden is",
    "in den ouderdom van",
    "Waarvan akte, welke is voorgelezen",
]

PRINTED_TEXT[1939] = [
    "Nr",
    "1939",
    "Blad nummer",
    "Heden",
    "negentienhonderd negen en dertig verscheen voor mij, hulpambtenaar van",
    "den Burgerlijken Stand op Curaçao",
    "oud",
    "jaren,",
    "wonende alhier, die verklaarde, daarvan uit eigen wetenschap kennis",
    "dragende, dat op",
    "dezes jaars",
    "middags te",
    "uur, alhier is overleden",
    "Waarvan akte, welke is voorgelezen",
]

#### 1940 and late: to be checked
